# Estadistica Aplicada
## Edwin Javier Hernández Rodríguez 2034175
### Objetos en Python

In [1]:
alumno1 = ['Juan', 'Perez', 23]

In [2]:
estadistica_g4 = ['Juan', 'Raul', 'Jimena', 'Alejandra']

In [3]:
estadistica_g4

['Juan', 'Raul', 'Jimena', 'Alejandra']

### Si queremos elegir a un elemento de la lista:
#### Nota: Python empieza a contar desde cero

In [13]:
estadistica_g4[2]

'Jimena'

In [12]:
estadistica_g4[0],estadistica_g4[2]

('Juan', 'Jimena')

Nota: en el siguiente ejemplo se ve como no toma la ultima posicion

In [16]:
estadistica_g4[0:3]

['Juan', 'Raul', 'Jimena']

In [17]:
estadistica_g4.append('Jaime')

In [19]:
estadistica_g4[0:5]

['Juan', 'Raul', 'Jimena', 'Alejandra', 'Jaime']

Para eliminar un elemento de la lista

In [20]:
estadistica_g4.remove('Jimena')

In [21]:
estadistica_g4

['Juan', 'Raul', 'Alejandra', 'Jaime']

### Para instalar librerías

In [26]:
pip install yfinance

Note: you may need to restart the kernel to use updated packages.


#### Así se importa una librería:

In [28]:
import yfinance as yf

In [29]:
import numpy as np

In [30]:
edades = [12, 23, 34, 45, 56]

In [31]:
type (edades)

list

In [32]:
edades = np.array(edades)

In [33]:
type(edades)

numpy.ndarray

In [34]:
np.sum(edades)

170

In [35]:
np.mean(edades)

34.0

In [36]:
np.prod(edades)

23647680

### **Poblacional**

In [37]:
np.var(edades)

242.0

In [38]:
np.std(edades)

15.556349186104045

### **Muestral**

In [41]:
np.var(edades, ddof = 1)

302.5

In [42]:
np.std(edades,ddof = 1)

17.392527130926087

### Para generar vectores

In [43]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [44]:
np.arange(0,101,15)

array([ 0, 15, 30, 45, 60, 75, 90])

In [45]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [46]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [47]:
np.full(6,8)

array([8, 8, 8, 8, 8, 8])

In [48]:
np.random.randint(0,25,10)

array([20, 16, 18,  3, 21,  0,  1, 21, 15,  4])

**Semilla**

In [51]:
np.random.seed(5)
aleatorios = np.random.randint(0,25,10)

**Para ordenarlos**

In [52]:
aleatorios = np.sort(aleatorios)

In [53]:
aleatorios

array([ 3,  4,  6,  7,  8,  9, 14, 15, 16, 22])