# Estadistica Aplicada
## Edwin Javier Hernández Rodríguez 2034175
### 3ra Sesión

In [1]:
import numpy as np

In [3]:
np.random.seed(30)
aleatorios = np.random.randint(0,20,10)

In [4]:
aleatorios = np.sort(aleatorios)

In [5]:
aleatorios

array([ 2,  3,  5,  5,  9, 12, 13, 13, 14, 17])

### Para elegir a una posicion del arreglo

In [6]:
aleatorios[2]

5

In [7]:
aleatorios [[2,3]]

array([5, 5])

In [8]:
aleatorios[aleatorios>10]

array([12, 13, 13, 14, 17])

In [9]:
np.random.seed(315)
aleatorios2 = np.random.randint(21,50,10)

#### Convertira aleatorios2 en un arreglo, le vamos a calcular la media y vamos a redondear a un decimal

### Función

In [10]:
round(np.mean(np.array(aleatorios2)),1)

30.4

### Método

In [11]:
np.array(aleatorios2).mean().round(1)

30.4

### TUPLA

In [13]:
tupla1 = (23, 45, "libro")
type(tupla1)

tuple

In [14]:
tupla1[2]

'libro'

### Diccionario

In [19]:
alumno1_dic = {'Nombre': 'Juan', 'Apellido': 'Perez', 'Edad': 23}
alumno1_dic

{'Nombre': 'Juan', 'Apellido': 'Perez', 'Edad': 23}

Clave......................................Clave2.....................................Clave3

In [20]:
alumno1_dic['Nombre']

'Juan'

In [21]:
alumno1_dic['Apellido']

'Perez'

In [22]:
estadistica_g5 = {'Nombre':['Ale','Jaime','Teo'],'Apellido':['Leos','Lara','Leal'],'Edad':[23,28,17]}

In [24]:
estadistica_g5['Nombre']

['Ale', 'Jaime', 'Teo']

#### Claves

In [25]:
estadistica_g5.keys()

dict_keys(['Nombre', 'Apellido', 'Edad'])

### Pandas

In [26]:
import pandas as pd

In [29]:
alumno1 = ['Juan', 'Perez', 23]
alumno2 = ['Raul', 'Gonzalez', 17]
alumno3 = ['Jimena', 'Rosas', 20]
alumno4 = ['Alejandra', 'Saldaña', 21]


In [30]:
clase_estadistica = [alumno1, alumno2, alumno3, alumno4]

In [31]:
clase_estadistica

[['Juan', 'Perez', 23],
 ['Raul', 'Gonzalez', 17],
 ['Jimena', 'Rosas', 20],
 ['Alejandra', 'Saldaña', 21]]

In [36]:
clase_estadistica = pd.DataFrame(clase_estadistica, columns = ['Nombre', 'Apellido', 'Edad'])

In [38]:
clase_estadistica['Edad en días'] = clase_estadistica['Edad']*365
clase_estadistica

Nombre  Apellido  Edad  Edad en días
0       Juan     Perez    23          8395
1       Raul  Gonzalez    17          6205
2     Jimena     Rosas    20          7300
3  Alejandra   Saldaña    21          7665

In [39]:
clase_estadistica['Estado de origen'] = ['Zacatecas', 'Nuevo Leon', 'Tamaulipas', 'Sinaloa']

In [40]:
clase_estadistica

Nombre  Apellido  Edad  Edad en días Estado de origen
0       Juan     Perez    23          8395        Zacatecas
1       Raul  Gonzalez    17          6205       Nuevo Leon
2     Jimena     Rosas    20          7300       Tamaulipas
3  Alejandra   Saldaña    21          7665          Sinaloa

#### 1.-Seleccion estandar
#### 2.- .loc
#### 3.- .iloc
#### 4.- Metodo (SQL)
#### 5.- Seleccion por condicionales

In [41]:
#Seleccion estandar
clase_estadistica['Apellido']

0       Perez
1    Gonzalez
2       Rosas
3     Saldaña
Name: Apellido, dtype: object

In [42]:
clase_estadistica[['Apellido', 'Edad']]

Apellido  Edad
0     Perez    23
1  Gonzalez    17
2     Rosas    20
3   Saldaña    21

In [43]:
clase_estadistica[0:2]

Nombre  Apellido  Edad  Edad en días Estado de origen
0   Juan     Perez    23          8395        Zacatecas
1   Raul  Gonzalez    17          6205       Nuevo Leon

In [45]:
clase_estadistica[0:2][['Apellido','Edad']]

Apellido  Edad
0     Perez    23
1  Gonzalez    17

### .iloc
Se tiene que dar posicion de filas y columnas

In [47]:
clase_estadistica.iloc[:,2]

0    23
1    17
2    20
3    21
Name: Edad, dtype: int64

In [48]:
#Si quisieramos nombre y edad
clase_estadistica.iloc[:,[0,2]]

Nombre  Edad
0       Juan    23
1       Raul    17
2     Jimena    20
3  Alejandra    21

In [49]:
#Nombre y edad de juan
clase_estadistica.iloc[0,[0,2]]

Nombre    Juan
Edad        23
Name: 0, dtype: object

In [50]:
#Para ver a juan y raul
clase_estadistica.iloc[0:2,[0,2]]

Nombre  Edad
0   Juan    23
1   Raul    17

### .loc (etiqueta / nombre)

In [52]:
clase_estadistica.loc[:,['Edad', 'Nombre']]

Edad     Nombre
0    23       Juan
1    17       Raul
2    20     Jimena
3    21  Alejandra

### Metodo SQL

In [53]:
clase_estadistica.Edad

0    23
1    17
2    20
3    21
Name: Edad, dtype: int64

### Seleccion por condicionales

In [54]:
clase_estadistica[clase_estadistica['Edad']>=18]

Nombre Apellido  Edad  Edad en días Estado de origen
0       Juan    Perez    23          8395        Zacatecas
2     Jimena    Rosas    20          7300       Tamaulipas
3  Alejandra  Saldaña    21          7665          Sinaloa

### Para ordenar

In [56]:
clase_estadistica.sort_values('Edad', ascending = False)

Nombre  Apellido  Edad  Edad en días Estado de origen
0       Juan     Perez    23          8395        Zacatecas
3  Alejandra   Saldaña    21          7665          Sinaloa
2     Jimena     Rosas    20          7300       Tamaulipas
1       Raul  Gonzalez    17          6205       Nuevo Leon

In [57]:
clase_estadistica.sort_values(['Apellido', 'Nombre'], ascending = [True,True])

Nombre  Apellido  Edad  Edad en días Estado de origen
1       Raul  Gonzalez    17          6205       Nuevo Leon
0       Juan     Perez    23          8395        Zacatecas
2     Jimena     Rosas    20          7300       Tamaulipas
3  Alejandra   Saldaña    21          7665          Sinaloa

In [58]:
clase_estadistica['Edad'].mean()

20.25

In [59]:
clase_estadistica['Edad'].var(ddof = 1)

6.25

In [60]:
clase_estadistica[clase_estadistica['Edad']>=18]

Nombre Apellido  Edad  Edad en días Estado de origen
0       Juan    Perez    23          8395        Zacatecas
2     Jimena    Rosas    20          7300       Tamaulipas
3  Alejandra  Saldaña    21          7665          Sinaloa

In [62]:
clase_estadistica[clase_estadistica['Edad']>=18]['Edad'].mean()

21.333333333333332

### Condicional

In [65]:
clase_estadistica['Mayoría de edad'] = np.where(clase_estadistica['Edad']>=18,'Mayor de edad', 'Menor de edad')
clase_estadistica

Nombre  Apellido  Edad  Edad en días Estado de origen Mayoría de edad
0       Juan     Perez    23          8395        Zacatecas   Mayor de edad
1       Raul  Gonzalez    17          6205       Nuevo Leon   Menor de edad
2     Jimena     Rosas    20          7300       Tamaulipas   Mayor de edad
3  Alejandra   Saldaña    21          7665          Sinaloa   Mayor de edad

In [67]:
#Ahora con mas condiciones
conditions = [clase_estadistica['Edad'] <= 17,
              clase_estadistica['Edad'] <= 23,
              clase_estadistica['Edad'] > 23]
choices = ['Preparatoria', 'estudia licenciatura', 'egresado']
clase_estadistica['edad escolar'] = np.select(conditions, choices, default = 'Invalid')
clase_estadistica

Nombre  Apellido  Edad  Edad en días Estado de origen Mayoría de edad  \
0       Juan     Perez    23          8395        Zacatecas   Mayor de edad   
1       Raul  Gonzalez    17          6205       Nuevo Leon   Menor de edad   
2     Jimena     Rosas    20          7300       Tamaulipas   Mayor de edad   
3  Alejandra   Saldaña    21          7665          Sinaloa   Mayor de edad   

           edad escolar  
0  estudia licenciatura  
1          Preparatoria  
2  estudia licenciatura  
3  estudia licenciatura